### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by WissamAntoun** [tuetschek/nrno_movies#1]
Is the dataset used in the paper available in public?

**Comment by tuetschek** [comment]
Hi, unfortunately it's not completely publicly available. You can try emailing and asking Pierre Lison (https://www.nr.no/~plison/about.html), who is the author of the paper that describes the dataset (https://www.nr.no/~plison/pdfs/cl/slt2016.pdf). 

Otherwise, if you just need the scripts from IMSDB, there's the Scriptbase dataset (https://github.com/EdinburghNLP/scriptbase), which is publicly available.

**Comment by WissamAntoun** [comment]
Thank you for the response
